### ISSUE TITLE
Documentation - How to trigger linter not obvious

### ISSUE THREAD

**Issue by nomad3k** [AtomLinter/linter-swagger#36]
I figured it out eventually, but it wasn't obvious how the linter gets triggered, and I couldn't tell if it was working and there were no errors in my doc or it had failed to install.  Eventually, I figured out that it was looking for a .json file with a "swagger" value in the root.  Could do with adding that the README.

**Comment by RiaanLab** [comment]
+1

**Comment by spoike** [comment]
https://github.com/AtomLinter/linter-swagger/blob/124c645/lib/validator.js#L54-L57

Yes, it uses a regular expression that looks for `swagger` field that has a version number as value in either json or yaml files before the actual validation kicks in. It was written this way because there is no specific scope for swagger files and you most likely don't want to validate all json or yaml files in a project.

It is also a **required** field according to the [Swagger 2.0 spec](http://swagger.io/specification/) under `Specification > Schema > Swagger Object`.

> **Required.** Specifies the Swagger Specification version being used. It can be used by the Swagger UI and other clients to interpret the API listing. The value MUST be "2.0".

So I'm not sure this is needed in the README because not having the `swagger` field would likely break other Swagger clients.

**Comment by spoike** [comment]
Added a PR that should fix this issue.
